[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
max-line-length = 100
disable = "W0511, W0212, I1101, C0115, C0116"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 100

[tool.coverage.report]
exclude_lines = [
  'raise TypeError("Parameter is not a list.")',
  'raise TypeError("All elements in the list must be of type cirq.Qid.")',
  "return str(self._module)",
  "return self._module.bitcode()",
  "return self._entry_point",
  "pass",
  "raise QirConversionError(err)",
  "raise NotImplementedError",
  "return NotImplemented",
  "def __repr__",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "logger.debug"
]